name: equate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  fl_chart: ^1.2.0
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.1
  lottie: ^3.1.0
  intl: ^0.20.3
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.0.0 # Ditambahkan untuk penyimpanan foto profil
  google_sign_in: ^7.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/